import { notFound } from "next/navigation";
import { incidents, locations, trip } from "@/lib/demo/data";
import { StatusPill } from "@/components/StatusPill";
import { acceptResponsibility, recordAction } from "../actions";
import { getPersistedIncident } from "@/lib/incidents/server";

export default async function IncidentPage({ params }: { params: Promise<{ incidentId: string }> }) {
  const id = (await params).incidentId;
  const incident = incidents.find((item) => item.id === id);
  if (!incident) notFound();
  const persisted = await getPersistedIncident(id);
  const state = persisted?.responseState ?? incident.responseState;
  const audit = persisted?.audit.length ? persisted.audit.map((event) => ({ id: event.id, action: event.action, at: new Date(event.created_at).toLocaleTimeString("en-NG", { hour: "2-digit", minute: "2-digit" }), detail: typeof event.safe_metadata?.note === "string" ? event.safe_metadata.note : "Persisted staff action", actor: "Authenticated staff" })) : incident.audit;
  return <main className="p-5 lg:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-[var(--muted)]">{incident.reference} · Journey {trip.code}</p><h1 className="display mt-1 text-4xl text-[var(--forest)]">{incident.title}</h1><div className="mt-3"><StatusPill tone={incident.routingClass === "PROTECTED" ? "orange" : "green"}>{state.replaceAll("_", " ")}</StatusPill></div></div><form action={acceptResponsibility}><input type="hidden" name="incidentId" value={id} /><button className="rounded-full bg-[var(--forest)] px-5 py-3 text-sm font-bold text-white">Accept responsibility</button></form></div><form action={recordAction} className="mt-7 rounded-3xl bg-white p-6"><input type="hidden" name="incidentId" value={id} /><label className="block text-sm font-bold" htmlFor="note">Record the next action</label><div className="mt-3 flex gap-3"><input id="note" name="note" required maxLength={1000} className="min-w-0 flex-1 rounded-xl border border-[var(--line)] px-4 py-3" placeholder="e.g. Replacement vehicle dispatched" /><button className="rounded-full bg-[var(--leaf)] px-5 py-3 font-bold text-white">Save action</button></div></form><div className="mt-7 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-3xl bg-white p-6"><p className="text-xs font-bold uppercase tracking-widest text-[var(--muted)]">Original source accounts</p><div className="mt-5 space-y-4">{incident.reports.map((report) => <article key={report.id} className="rounded-2xl border border-[var(--line)] p-5"><strong>{report.reporterRole === "PASSENGER" && incident.routingClass === "PROTECTED" ? "Passenger · identity protected" : report.reporterRole}</strong><p className="mt-3 leading-7">“{report.originalText}”</p><p className="mt-3 text-xs text-[var(--muted)]">{report.channel} · Original preserved</p></article>)}</div></section><aside className="space-y-6"><div className="rounded-3xl bg-white p-6"><p className="text-xs font-bold uppercase tracking-widest text-[var(--muted)]">Locations</p>{locations.map((location) => <div key={location.id} className="flex justify-between border-b border-[var(--line)] py-3"><span className="text-sm">{location.source}</span><StatusPill tone={location.freshness === "ACTIVE" ? "green" : "orange"}>{location.freshness}</StatusPill></div>)}</div><div className="rounded-3xl bg-white p-6"><p className="text-xs font-bold uppercase tracking-widest text-[var(--muted)]">Persisted audit timeline</p><div className="mt-5 space-y-5">{audit.map((event) => <div key={event.id}><p className="text-sm font-bold">{event.action.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-[var(--muted)]">{event.detail} · {event.actor}</p></div>)}</div></div></aside></div></main>;
}
