import Link from "next/link";
import { Brand } from "@/components/Brand";
import { StatusPill } from "@/components/StatusPill";

export default function Home() {
  return <main>
    <section className="grid-noise min-h-[92vh] overflow-hidden bg-[var(--paper)]">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><Brand /><div className="hidden items-center gap-8 text-sm font-semibold md:flex"><Link href="/report">Report a concern</Link><Link href="/judge">Judge mode</Link><Link href="/privacy">Privacy</Link></div><Link href="/dashboard" className="rounded-full bg-[var(--forest)] px-5 py-3 text-sm font-bold text-white">Open IrinAbo Desk ↗</Link></nav>
      <div className="mx-auto grid max-w-7xl gap-14 px-6 pb-24 pt-12 lg:grid-cols-[1.08fr_.92fr] lg:px-10 lg:pt-20">
        <div className="flex flex-col justify-center"><StatusPill tone="lime">WORKING PROOF OF CONCEPT</StatusPill><h1 className="display mt-7 max-w-3xl text-6xl leading-[.94] tracking-[-.045em] text-[var(--forest)] sm:text-7xl lg:text-[88px]">A safer thread through every journey.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--muted)]">Report a journey concern through a familiar channel. IrinAbo keeps the original source, protects sensitive reports and makes the next responsible action visible.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/report" className="rounded-full bg-[var(--orange)] px-7 py-4 font-bold text-white">Try the report flow →</Link><Link href="/journey/demo-tw204" className="rounded-full border border-[var(--line)] bg-white px-7 py-4 font-bold text-[var(--forest)]">Open Journey Mode</Link></div><p className="mt-6 text-xs uppercase tracking-[.13em] text-[var(--muted)]">Demo organisation and incidents are fictional · No emergency-service integration</p></div>
        <div className="relative min-h-[560px]"><div className="absolute inset-6 rotate-3 rounded-[36px] bg-[var(--lime)]" /><div className="paper-shadow absolute inset-0 overflow-hidden rounded-[36px] border border-white/60 bg-[var(--forest)] text-white"><div className="flex items-center justify-between border-b border-white/10 px-7 py-5"><span className="text-sm font-bold">Journey TW204</span><StatusPill tone="lime">IN PROGRESS</StatusPill></div><div className="p-7"><p className="text-xs uppercase tracking-[.16em] text-white/55">Ikorodu → Ibadan</p><h2 className="display mt-2 text-4xl">One report. A visible response.</h2><div className="mt-8 space-y-4">{[['11:42','Report received','Original WhatsApp message preserved'],['11:42','Protected route locked','Ordinary garage staff cannot view the case'],['11:44','Independent fallback due','Responsibility still awaiting acceptance']].map(([time,title,detail], index) => <div key={title} className="flex gap-4"><div className="flex flex-col items-center"><span className={`grid size-8 place-items-center rounded-full ${index === 2 ? 'bg-[var(--orange)]' : 'bg-[var(--lime)] text-[var(--forest)]'}`}>{index === 2 ? '!' : '✓'}</span>{index < 2 && <span className="h-12 w-px bg-white/20" />}</div><div><p className="font-bold">{title} <span className="ml-2 text-xs font-normal text-white/45">{time}</span></p><p className="mt-1 text-sm leading-6 text-white/60">{detail}</p></div></div>)}</div><div className="mt-7 rounded-2xl border border-white/10 bg-white/[.07] p-5"><p className="text-xs uppercase tracking-widest text-white/45">Reporter control</p><p className="mt-2 font-bold">Identity protected</p><p className="mt-1 text-sm text-white/60">The service and messaging provider may still process the sender&apos;s number.</p></div></div></div></div>
      </div>
    </section>
    <section className="bg-[var(--forest)] px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--lime)]">Built around evidence, not promises</p><div className="mt-6 grid gap-8 md:grid-cols-3">{[['01','Retain the source','Original reports, channels and timestamps remain linked to every derived summary.'],['02','Protect the route','Staff-involved reports bypass the ordinary garage chain through fixed rules.'],['03','Show the follow-up','Notification, acceptance, action and outcome are separate, visible events.']].map(([n,title,copy]) => <div key={n} className="border-t border-white/20 pt-6"><span className="text-sm text-white/40">{n}</span><h3 className="display mt-8 text-3xl">{title}</h3><p className="mt-3 leading-7 text-white/60">{copy}</p></div>)}</div></div></section>
  </main>;
}
