"use client";
import { useState } from "react";

type Timeline = { audit: Array<{ id: string; action: string; created_at: string; safe_metadata: Record<string, unknown> }>; feedback: string | null } | null;

export function Receipt({ timeline, demo = false }: { timeline: Timeline; demo?: boolean }) {
  const [state, setState] = useState<"open" | "matches" | "review" | "error">(timeline?.feedback === "MATCHES" ? "matches" : timeline?.feedback === "NOT_RESOLVED" ? "review" : "open");
  const submit = async (feedback: "MATCHES" | "NOT_RESOLVED") => { const response = await fetch("/api/receipts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ feedback, demo }) }); setState(response.ok ? (feedback === "MATCHES" ? "matches" : "review") : "error"); };
  const events = timeline?.audit ?? [];
  return <div className="paper-shadow w-full max-w-xl rounded-[32px] bg-white p-7 sm:p-9"><p className="text-xs font-bold uppercase tracking-widest text-[var(--leaf)]">Resolution receipt · IRN-204-031</p><h1 className="display mt-2 text-4xl">Your report&apos;s follow-up</h1><p className="mt-3 text-sm text-[var(--muted)]">This receipt shows recorded actions. It does not prove that an outcome occurred exactly as recorded.</p>{events.length > 0 && <div className="mt-7 rounded-2xl bg-stone-50 p-5"><p className="text-xs font-bold uppercase tracking-widest text-[var(--muted)]">Persisted activity</p><div className="mt-4 space-y-3">{events.map((event) => <div key={event.id}><p className="font-bold">{event.action.replaceAll("_", " ")}</p><p className="text-xs text-[var(--muted)]">{new Date(event.created_at).toLocaleString("en-NG")} · {typeof event.safe_metadata.note === "string" ? event.safe_metadata.note : "Recorded by IrinAbo"}</p></div>)}</div></div>}{demo && <p className="mt-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-900">Demo feedback is acknowledged locally and does not change shared metrics.</p>}{state === "open" ? <div className="mt-8 border-t border-[var(--line)] pt-6"><p className="font-bold">Does this outcome match what happened?</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={() => submit("MATCHES")} className="rounded-full border border-[var(--line)] px-5 py-3 font-bold">Yes, it matches</button><button onClick={() => submit("NOT_RESOLVED")} className="rounded-full bg-[var(--orange)] px-5 py-3 font-bold text-white">This is not resolved</button></div></div> : <div className="mt-8 rounded-2xl bg-orange-50 p-5"><strong>{state === "error" ? "Could not record feedback" : state === "review" ? "Review requested" : "Feedback recorded"}</strong><p className="mt-1 text-sm text-[var(--muted)]">{state === "error" ? "Please try again." : demo ? "This demo response was not written to the shared incident history." : "Your response was appended to the incident history."}</p></div>}</div>;
}
