"use client";
import { useState } from "react";
import Link from "next/link";

export function ReportFlow() {
  const [step, setStep] = useState(1);
  const [text, setText] = useState("Our bus has stopped near the interchange. The driver is threatening passengers who try to call the garage. I need help.");
  const [protectedRoute, setProtectedRoute] = useState(true);
  return <div className="paper-shadow mx-auto w-full max-w-2xl rounded-[32px] bg-white p-6 sm:p-9">
    <div className="flex items-center gap-2">{[1,2,3].map(n=><span key={n} className={`h-1.5 flex-1 rounded-full ${n<=step?'bg-[var(--leaf)]':'bg-[var(--line)]'}`} />)}</div>
    {step===1 && <><p className="mt-8 text-xs font-bold uppercase tracking-widest text-[var(--leaf)]">Step 1 of 3 · Original report</p><h1 className="display mt-2 text-4xl">What happened on your journey?</h1><p className="mt-3 leading-7 text-[var(--muted)]">Your message is stored before any summary is made. For immediate danger, contact an appropriate local emergency service directly.</p><label className="mt-7 block text-sm font-bold" htmlFor="report">Report</label><textarea id="report" value={text} onChange={e=>setText(e.target.value)} className="mt-2 min-h-40 w-full rounded-2xl border border-[var(--line)] bg-[var(--paper)] p-4 outline-none focus:border-[var(--leaf)]"/><label className="mt-5 flex items-center gap-3 rounded-2xl border border-orange-200 bg-orange-50 p-4"><input type="checkbox" defaultChecked className="size-5 accent-[var(--orange)]"/><span><strong className="block">I need immediate help</strong><span className="text-sm text-[var(--muted)]">The report is routed as soon as it reaches the server.</span></span></label><button disabled={!text.trim()} onClick={()=>setStep(2)} className="mt-7 w-full rounded-full bg-[var(--forest)] px-6 py-4 font-bold text-white disabled:opacity-40">Store report and continue →</button></>}
    {step===2 && <><p className="mt-8 text-xs font-bold uppercase tracking-widest text-[var(--leaf)]">Step 2 of 3 · Routing choice</p><h1 className="display mt-2 text-4xl">Does this involve the driver or transport staff?</h1><p className="mt-3 leading-7 text-[var(--muted)]">Yes and prefer not to say use a restricted safety route. This choice controls visibility; it does not decide whether an account is true.</p><div className="mt-7 grid gap-3">{[[true,'Yes — staff are involved','Use the identity-protected safety route'],[false,'No','Use the ordinary garage coordinator route']].map(([value,label,desc])=><button key={label as string} onClick={()=>setProtectedRoute(value as boolean)} className={`rounded-2xl border p-5 text-left ${protectedRoute===value?'border-[var(--leaf)] bg-emerald-50':'border-[var(--line)]'}`}><strong className="block">{label as string}</strong><span className="mt-1 block text-sm text-[var(--muted)]">{desc as string}</span></button>)}<button onClick={()=>setProtectedRoute(true)} className="rounded-2xl border border-[var(--line)] p-5 text-left"><strong className="block">Prefer not to say</strong><span className="mt-1 block text-sm text-[var(--muted)]">Uses the identity-protected route.</span></button></div><div className="mt-6 rounded-2xl bg-[var(--forest)] p-5 text-white"><strong>Identity-protected is not anonymous.</strong><p className="mt-1 text-sm leading-6 text-white/65">IrinAbo and its messaging provider may process your phone number. Ordinary garage staff will not see your identity or report content.</p></div><button onClick={()=>setStep(3)} className="mt-7 w-full rounded-full bg-[var(--orange)] px-6 py-4 font-bold text-white">Lock route and submit →</button></>}
    {step===3 && <div className="py-10 text-center"><span className="mx-auto grid size-20 place-items-center rounded-full bg-[var(--lime)] text-3xl text-[var(--forest)]">✓</span><p className="mt-7 text-xs font-bold uppercase tracking-widest text-[var(--leaf)]">Report IRN-204-031 received</p><h1 className="display mt-2 text-4xl">Your report is preserved.</h1><p className="mx-auto mt-3 max-w-md leading-7 text-[var(--muted)]">{protectedRoute?'The protected safety route is locked. Ordinary garage staff cannot view this case.':'The ordinary garage coordinator route is locked.'} Responsibility has not yet been accepted.</p><div className="mt-7 rounded-2xl border border-[var(--line)] p-5 text-left"><p className="text-xs uppercase tracking-widest text-[var(--muted)]">Demonstration status</p><div className="mt-3 flex items-center justify-between"><strong>Received by server</strong><span className="text-emerald-700">Recorded ✓</span></div><div className="mt-3 flex items-center justify-between"><strong>Responsible route notified</strong><span className="text-orange-700">Simulated</span></div></div><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/receipt/demo-receipt" className="rounded-full bg-[var(--forest)] px-6 py-3 font-bold text-white">View receipt</Link><Link href="/judge" className="rounded-full border border-[var(--line)] px-6 py-3 font-bold">See capability labels</Link></div></div>}
  </div>;
}
