import { requireStaff } from "@/lib/auth/staff";
import { createServerSupabase } from "@/lib/supabase/server";
import { addStaff, deactivateStaff } from "./actions";

export default async function StaffPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const staff = await requireStaff(["ADMIN"]);
  const query = await searchParams;
  const db = createServerSupabase();
  const { data: members } = db ? await db.from("company_staff").select("id,full_name,username,role,active,created_at").eq("organisation_id", staff.organisationId).order("created_at", { ascending: true }) : { data: [] };
  return <main className="max-w-5xl p-5 lg:p-8"><p className="text-xs font-bold uppercase tracking-widest text-[var(--leaf)]">Company administration</p><h1 className="display mt-2 text-4xl text-[var(--forest)]">Staff</h1><p className="mt-3 text-[var(--muted)]">Add people who can handle reports. Keep each username and access code private.</p>{query.error && <p role="alert" className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{query.error}</p>}{query.success && <p className="mt-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900">{query.success}</p>}<section className="mt-8 rounded-3xl border border-black/5 bg-white p-6"><h2 className="display text-2xl">Add staff member</h2><form action={addStaff} className="mt-5 grid gap-3 sm:grid-cols-2"><input name="fullName" required placeholder="Full name" className="rounded-xl border border-[var(--line)] px-4 py-3"/><input name="username" required placeholder="Username (for staff login)" className="rounded-xl border border-[var(--line)] px-4 py-3"/><select name="role" className="rounded-xl border border-[var(--line)] px-4 py-3"><option>STAFF</option><option>COORDINATOR</option><option>SAFETY_COORDINATOR</option><option>ADMIN</option></select><input name="accessCode" required inputMode="numeric" pattern="[0-9]{6}" placeholder="6-digit access code" className="rounded-xl border border-[var(--line)] px-4 py-3"/><button className="rounded-full bg-[var(--forest)] px-5 py-3 font-bold text-white sm:col-span-2">Add staff member</button></form><p className="mt-4 text-sm text-[var(--muted)]">Staff login identities are being added next; for now, staff records can be assigned to reports from the dashboard.</p></section><section className="mt-5 rounded-3xl border border-black/5 bg-white p-6"><h2 className="display text-2xl">Staff list</h2>{members?.length?<div className="mt-5 space-y-3">{members.map((member)=><div key={member.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--line)] p-4"><div><p className="font-bold">{member.full_name}</p><p className="text-sm text-[var(--muted)]">@{member.username} · {member.role.replaceAll("_"," ")}</p></div><div className="flex items-center gap-3"><span className={`text-xs font-bold ${member.active?"text-emerald-700":"text-[var(--muted)]"}`}>{member.active?"Active":"Inactive"}</span>{member.active&&<form action={deactivateStaff}><input type="hidden" name="id" value={member.id}/><button className="text-sm font-bold text-red-700">Deactivate</button></form>}</div></div>)}</div>:<p className="mt-4 rounded-2xl bg-stone-50 p-4 text-sm text-[var(--muted)]">No staff members added yet.</p>}</section></main>;
}
